### ISSUE TITLE
What's the advantage compared with pure lidar based slam?

### ISSUE THREAD

**Issue by YiChenCityU** [johannes-graeter/limo#14]
As pure 3d lidar slam is robust and precise in localization compared with visual slam, why we have to use lidar in this way  if we have both of the sensor?

**Comment by johannes-graeter** [comment]
good question. 
So firstly this is a research topic so I was interested on how precise can I get with mainly using the camera and only lidar for the depth of the image measurements. My hope is that if you add "pure" lidar methods to the optimization problem we will win accuracy, since tracking features is a lot easier in the camera than in the lidar.
Secondly I hope this principle looses less accuracy when you use a lower resolution lidar than traditional pure lidar methods. However these are just assumptions/motivations which I did not evaluate (yet).
