### ISSUE TITLE
Build with Ubuntu 16.04

### ISSUE THREAD

**Issue by yjsx** [johannes-graeter/limo#47]
Hello！
I'm very interested in limo, but I met some question when I tried to build limo. Can I still build limo with Ubuntu 16.04 now？I notice that you may be using ros-melodic now, and  when I tried to build, I met so much error with ros-kinetic. Part of them is showing in the picture.
![image](https://user-images.githubusercontent.com/25319512/78402437-2c79b100-762d-11ea-8ce8-9ddaae274b00.png)
![image](https://user-images.githubusercontent.com/25319512/78402515-474c2580-762d-11ea-9f64-8cd34c460cb6.png)
![image](https://user-images.githubusercontent.com/25319512/78402548-5337e780-762d-11ea-93a1-f73009b1a98e.png)
Or could you give me some suggestion to solve them? 
Thank you very much!

**Comment by johannes-graeter** [comment]
Hi there,

since most people where interested in melodic and kinetic seems kind of outdated, I switched to melodic per default.
There is two ways: 
1. You could checkout an older version of the repo (f.e. https://github.com/johannes-graeter/limo/commit/b6504b95743ef311646efdfd928da22233733814) but make sure, that you also checkout a commit around the same date for the other repos needed (listed in install_repos)

2. You can try out the brand new docker image (that still uses melodic though, but you could have it beside the other kinetic based elements you use.)

**Comment by johannes-graeter** [comment]
Also if you just want to develop on VO, I am working on a python interface for limo right now.
A first draft should be ready by Sunday.

Best,

Johannes
