### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hshsjkjy** [johannes-graeter/limo#50]
While running step 11/17 : RUN /bin/bash -c 'source /opt/ros/melodic/setup.bash && catkin build'
I met such a problem 
![Screenshot from 2020-06-25 02-53-56](https://user-images.githubusercontent.com/37426374/85615789-56bc9700-b68f-11ea-8fe7-3d3debb17d77.png)
and I have already installed the Eigen
![2](https://user-images.githubusercontent.com/37426374/85616072-ccc0fe00-b68f-11ea-8c1a-540655bb619d.png)

How can I solve this bug？

**Comment by johannes-graeter** [comment]
Hi,

thanks for the interest in my work and the usage of the new docker container :)

Since the container does install libeigen there must be some changes in the links of eigen. In this issue https://stackoverflow.com/questions/23284473/fatal-error-eigen-dense-no-such-file-or-directory#25537967 there was a similar problem. I will need to debug it further, i will give it a spin this weekend :)

Thanks for your patience!
Best,
Johannes

**Comment by hshsjkjy** [comment]
Thank you for your reply. I did create symlinks to solve the problem, but it doesn`t work. I wonder if I should re-install the libeigen.
Looking forward to your solution.

**Comment by johannes-graeter** [comment]
Hi:)

did you do the link on your machine or in the Dockerfile (that is building the docker image).
please consider that you are building a docker image, so what you have installed (and linked) on your machine ist not relevant for the container (which is the beauty of it :) since you have an isolated system then) what you can do is add a RUN statement in the Dockerfile, that does the link to eigen and rebuild it :)

Thanks for your effort!
Best
Johannes

**Comment by hshsjkjy** [comment]
Thanks for reminding me of that, now it works well by creating symlinks in the Dockerfile.
Sorry to disturb you for such a stupid bug, hope you have a good day:)

**Comment by johannes-graeter** [comment]
> Thanks for reminding me of that, now it works well by creating symlinks in the Dockerfile.
> 
> Sorry to disturb you for such a stupid bug, hope you have a good day:)


No worries, there is no such thing as stupid bugs ;)
I am happy that you are interested in my code :)!
I would be happy if you would add it to the project as your contribution. Fork the repo make branch and file a pull request:) in that way your contrib is documented ;)

Best, Johannes
