### ISSUE TITLE
Demo shows nothing.  Is there a "fixed frame" that I should be looking at?  Or how to config rviz

### ISSUE THREAD

**Issue by MontyTHall** [johannes-graeter/limo#9]
"map" doesn't seem to do anything in rviz.  "/estimate/active_path" seems to show a path - going up in a straight line - wasn't quite expecting that.  I was expecting a path in the plane not out of the plane.  The segmentation and color images seem to work - so the bag file and segmenter are working.

**Comment by johannes-graeter** [comment]
if the acttive path works, at least the tool is running :) that is the final output of LIMO...
Sounds to me like a problem with the rviz configuration file. I will update it on monday.

**Comment by johannes-graeter** [comment]
Sorry for the delay, rviz file should be fixed now. Just open the rviz file in demo_keyframe_bundle_adjustment_meta/res/default.rviz

**Comment by andriiD** [comment]
@johannes-graeter Should I rebuild the project in the virtual image? Because rviz shows empty grid (there is also a notification in the Displays bar "Global Status: Error, Fixed frame [map] does not exist" ). Rviz shows the same time as in the "2)rosbag play" terminal and the data about movement is shown in "3)roslaunch" terminal ()
To run everything I execute following commands in different terminals:
1) roscore
2) rosbag play ~/kitti_seqs/04.bag -r 0.1 --pause --clock
unpause here
3)
source devel_limo_release/setup.bash && roslaunch demo_keyframe_bundle_adjustment_meta kitti_standalone.launch
4) rviz src/limo/demo_keyframe_bundle_adjustment_meta/res/default.rviz

**Comment by johannes-graeter** [comment]
try rviz -d src/limo/demo_keyframe_bundle_adjustment_meta/res/default.rviz

Perhaps

**Comment by johannes-graeter** [comment]
if that doesn't work try local_cs as fixed frame.
The poses should be dumped to /tmp/poses_dump.txt you can have a look at them to see if the program itself runs.

**Comment by andriiD** [comment]
> try rviz -d src/limo/demo_keyframe_bundle_adjustment_meta/res/default.rviz
> 
Worked. Thank you. Could you post a screenshot from the demo ? To be sure that it works correctly
